bbs/max_range: 15.0
bbs/min_tx: -50.0
bbs/max_tx: 50.0
bbs/min_ty: -50.0
bbs/max_ty: 50.0
bbs/min_theta: -3.15
bbs/max_theta: 3.15

bbs/map_min_z: 2.0
bbs/map_max_z: 2.4
bbs/map_width: 512
bbs/map_height: 1024
bbs/map_resolution: 0.5
bbs/map_pyramid_level: 6
bbs/max_points_per_cell: 5

bbs/scan_min_z: -0.2
bbs/scan_max_z: 0.2
