# estimation parameters
ransac/voxel_based: True
ransac/max_iterations: 1000000
ransac/matching_budget: 10000
ransac/max_correspondence_distance: 1.0
ransac/similarity_threshold: 0.5
ransac/correspondence_randomness: 2
ransac/inlier_fraction: 0.25

# valid transformation range
ransac/x_min: -100.0
ransac/x_max: 100.0
ransac/y_min: -100.0
ransac/y_max: 100.0
ransac/z_min: -10.0
ransac/z_max: 10.0

ransac/roll_min: -0.7
ransac/roll_max: 0.7
ransac/pitch_min: -0.7
ransac/pitch_max: 0.7
ransac/yaw_min: -3.15
ransac/yaw_max: 3.15
